version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    container_name: pg_database
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "3208:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - drizzle_network

  drizzle:
    build:
      context: ./drizzle
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://myuser:mypassword@db:5432/mydb
    ports:
      - "4983:3209"
    command: npm run db:studio
    depends_on:
      - db
    networks:
      - drizzle_network

volumes:
  db_data:

networks:
  drizzle_network:
    driver: bridge