version: '3.8'

services:
  db:
    image: postgres:15
    container_name: pg_database
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - pgnetwork

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "5051:8080"  # Adminer runs on port 8080 inside container
    networks:
      - pgnetwork
    depends_on:
      - db

volumes:
  db_data:

networks:
  pgnetwork:
